language: python

sudo: required
dist: trusty

deploy:
  provider: pages
  local_dir: ${TRAVIS_BUILD_DIR}/docs/build/html
  skip_cleanup: true
  repo: qmlcode/qmlcode.github.io
  target_branch: master
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: documentation

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq gcc gfortran libblas-dev liblapack-dev
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8
 
 - |
   if [ ${TRAVIS_PYTHON_VERSION:0:1} = 3 ]; then
       sudo apt-get install python3-numpy
       python3 setup.py install
   elif [ ${TRAVIS_PYTHON_VERSION} = "2.7" ]; then
       sudo apt-get install python-numpy
       python2 setup.py install
       pip2 install sphinx
       pip2 install sphinx-rtd-theme
       python2 setup.py build
       python2 setup.py install
       cd ${TRAVIS_BUILD_DIR}/docs
       make html

   else
       echo "ERROR: Unknown Python version."
   fi


before_script:
 - cd ${TRAVIS_BUILD_DIR}/tests/

script:
 - nosetests -v

notifications:
  email: false
