language: python

sudo: required
dist: trusty

deploy:
  provider: pages
  skip_cleanup: true

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq gcc gfortran libblas-dev liblapack-dev
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8

 - |
   if [ ${TRAVIS_PYTHON_VERSION:0:1} = 3 ]; then
       sudo apt-get install python3-numpy
       python3 setup.py install
   elif [ ${TRAVIS_PYTHON_VERSION} = "2.7" ]; then
       sudo apt-get install python-numpy
       python2 setup.py build
       python2 setup.py install

   else
       echo "ERROR: Unknown Python version."
   fi

   cd ${TRAVIS_BUILD_DIR}/docs
   make html


before_script:
 - cd ${TRAVIS_BUILD_DIR}/tests/

script:
 - nosetests -v

after_success: 
 - |
   cd ${TRAVIS_BUILD_DIR}/docs/

   git init
   git checkout -b gh-pages
   git add .
   git -c user.name='travis' -c user.email='travis' commit -m init

   # Make sure to make the output quiet, or else the API token will leak!
   # This works because the API key can replace your password.
   git push -f -q https://andersx:$GH_TOKEN@github.com/qmlcode/qmlcode.github.io gh-pages 
   cd "$TRAVIS_BUILD_DIR"
