language: python

sudo: required
dist: trusty

deploy:
  provider: pages
  skip_cleanup: true
  repo: qmlcode/qmlcode.github.io
  target_branch: master
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: documentation

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq gcc gfortran libblas-dev liblapack-dev
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8
 - sudo apt-get install python-numpy
 - pip2 install sphinx
 - pip2 install sphinx-rtd-theme
 - python2 setup.py build
 - python2 setup.py install
 - cd ${TRAVIS_BUILD_DIR}/docs
 - make html


before_script:
 - cd ${TRAVIS_BUILD_DIR}/tests/

script:
 - nosetests -v

after_success: 
 - cd ${TRAVIS_BUILD_DIR}/docs/build/html
 - pwd
 - ls

notifications:
  email: false
